In [1]:
import IPython.display as ipd
import os
import sys
sys.path.append(os.path.join(os.getcwd(), 'evaluation'))
import numpy as np
import matplotlib.pyplot as plt
import torch
import soundfile as sf
import librosa
from build_model import build_model
from evaluation.loss_mse import rmse_td, rmse_fd, rmse_frame
from test_result import resynthesis

ModuleNotFoundError: No module named 'pystoi'

In [2]:
root_dir = '/Users/xiaoyu/WorkStation/Project_rvae/test_eval'
cfg_file = os.path.join(root_dir, 'config.ini')
w_file = os.path.join(root_dir, 'RVAE_final_epoch115.pt')
audio_file_list = ['/Users/xiaoyu/WorkStation/Project_rvae/Data/clean_speech/wsj0_si_et_05/440/440c0201.wav']

In [3]:
result_dir, _ = resynthesis(cfg_file, w_file, audio_file_list)

print(result_dir)

<Figure size 432x288 with 0 Axes>

In [3]:
file_orig = os.path.join(root_dir, 'audio_orig.wav')
file_recon = os.path.join(root_dir, 'audio_recon.wav')
x, _ = sf.read(file_orig)
x_recon, _ = sf.read(file_recon)


wlen_sec = 64e-3
hop_percent = 0.25
fs = 16000
nfft = np.int(np.power(2, np.ceil(np.log2(wlen_sec * fs))))
# window length <= nfft (equal to nfft by default)
wlen = nfft
# hop: number of audio samples between adjacent STFT columns
hop = np.int(hop_percent * wlen)
# a vector or array of length nfft (sin function, 0 ~ pi)
win = np.sin(np.arange(0.5, wlen+0.5) / wlen * np.pi)

print(rmse_td(x, x_recon))
print(rmse_fd(x, x_recon, wlen_sec, nfft, hop, wlen, win))
print(rmse_frame(x, x_recon, nfft, win))

In [7]:
from configparser import ConfigParser
class myconf(ConfigParser):
    def __init__(self,defaults=None):
        ConfigParser.__init__(self,defaults=None)
    def optionxform(self, optionstr):
        return optionstr
    
cfg_file = '/Users/xiaoyu/WorkStation/Project_rvae/rvae-speech/config/cfg_debug_storn.ini'
cfg = myconf()
cfg.read(cfg_file)
cfg.has_option('Network', 'tag')


False

In [42]:
import torch 
import torch.nn as nn
import numpy as np
SEED = 0
torch.manual_seed(SEED)
torch.cuda.manual_seed(SEED)
np.random.seed(SEED)

In [43]:
a = np.array([0,0,0,0])
b = np.array([1,1,1,1])
mean = torch.as_tensor(a, dtype=torch.float32)
sig = torch.as_tensor(b, dtype=torch.float32)

In [91]:
SEED = 0
torch.manual_seed(SEED)
torch.cuda.manual_seed(SEED)
print(torch.normal(mean,sig))
print(torch.randn_like(mean).mul(sig).add_(mean))
print(torch.randn_like(mean))

tensor([ 1.5410, -0.2934, -2.1788,  0.5684])
tensor([-1.0845, -1.3986,  0.4033,  0.8380])
tensor([-0.7193, -0.4033, -0.5966,  0.1820])


In [80]:

np.random.randn(1)

array([-0.97727788])